baseURL: https://www.janhendrikpeters.de
languageCode: "en-us"
title: "JHP's blog"
theme: "ananke"
resourceDir: "../resources"

DefaultContentLanguage: "en"
SectionPagesMenu:
pagination:
  pagerSize: 9
enableEmoji: true
enableRobotsTXT: true
params:
  mainpagetitle: JHP's Blog
  mainSections:
    - post
  showhugo: true
  recent_posts_number: 3
  author: Jan-Hendrik Peters
  site_logo: /img/jhp.png
  ananke:
    social:
      share:
        networks:
          - email
          - linkedin
          - mastodon
      follow:
        networks:
          - github
          - mastodon
          - linkedin
      github:
        username: github
      mastodon:
        username: nyanhp
        profilelink: https://metalhead.club/@nyanhp
        rel: me
      linkedin:
        profilelink: https://www.linkedin.com/in/jan-hendrik-peters-251392139

copyright: Jan-Hendrik Peters
languages:
  en:
    cascade:
      featured_image: false
    weight: 1
    contentDir: "content/en"
    params:
      read_more_copy: Read More
      mainpagesubtitle: Random Stuff
      mainpagedesc: "Peruse the content! No comments enabled because I don't have time to moderate. Feel free to use GitHub for that!"
      
    menu:
      main:
        - identifier: GPG
          name: GPG
          url: https://keys.openpgp.org/vks/v1/by-fingerprint/1B65D90FDB7A578E7D81CB14FE998908CF4006EA
          weight: 40
        - identifier: "about"
          name: "About"
          url: "/about/"
          weight: 30
        - identifier: "portfolio"
          name: "My portfolio"
          url: "/portfolio/"
          weight: 20
        - identifier: "recipe"
          name: "All recipes"
          url: "/recipe/"
          weight: 15
        - identifier: "post"
          name: "All posts"
          url: "/post/"
          weight: 10
    taxonomies:
      category: "categories"
      tag: "tags"
  de:
    cascade:
      featured_image: false
    weight: 2
    contentDir: "content/de"
    params:
      read_more_copy: Weiterlesen
      mainpagesubtitle: Allerlei Krempel
      mainpagedesc: "Viel Spaß mit den Inhalten! Ich habe keine Zeit, Kommentare zu moderieren, daher sind sie deaktiviert. Ihr könnt einzelne Seiten gerne bei GitHub kommentieren!"

    menu:
      main:
        - identifier: GPG
          name: GPG
          url: https://keys.openpgp.org/vks/v1/by-fingerprint/1B65D90FDB7A578E7D81CB14FE998908CF4006EA
          weight: 40
        - identifier: "about"
          name: "Über"
          url: "/de/about/"
          weight: 30
        - identifier: "portfolio"
          name: "Mein Portfolio"
          url: "/de/portfolio/"
          weight: 20
        - identifier: "recipe"
          name: "Alle Rezepte"
          url: "/de/recipe/"
          weight: 15
        - identifier: "post"
          name: "Alle Beiträge"
          url: "/de/post/"
          weight: 10
    taxonomies:
      category: "Kategorien"
      tag: "Schlagwörter"
