
name: Publish content
on:
    label:
      types:
        - created
    push:
      branches:
        - main
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build static content
        steps:            
            - uses: actions/checkout@v3
            - run: hugo
    publish:
        name: Deploy
        runs-on: ubuntu-latest
        steps:    
        - name: Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
              server: ${{ secrets.sftp }}
              username: ${{ secrets.user }}
              password: ${{ secrets.password }}
              protocol: sftp
              port: 22
              local-dir: ./public/
              server-dir: janhendrikpetersde/